# Generated by Django 5.1.4 on 2024-12-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
    ]
