# Generated by Django 5.1.3 on 2024-12-13 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderacall'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderacall',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderacall',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
